import Footer from "./global-components/Footer";
import "./globals.css";
import Navwrapper from "./global-components/Navwrapper";
import GlobalState from "./Contexts/GlobalState";
import MainWrapper from "./global-components/MainWrapper";
export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({ children }) {
  return (
    <GlobalState>
      <html lang="en">
        <body>
          <Navwrapper />
          <MainWrapper>{children}</MainWrapper>
          <Footer />
        </body>
      </html>
    </GlobalState>
  );
}
