import Footer from './global-components/Footer';
import Navbar from './global-components/Navbar';
import './globals.css';
export const metadata = {
	title: 'Next.js',
	description: 'Generated by Next.js',
};

export default function RootLayout({ children }) {
	return (
		<html lang='en'>
			<body>
				<Navbar />
				<main className='mainContainer'>{children}</main>
				<Footer />
			</body>
		</html>
	);
}
