import Footer from "./global-components/Footer";
import "./globals.css";
import Navwrapper from "./global-components/Navwrapper";
export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Navwrapper />
        <main className="mainContainer bg-white">{children}</main>
        <Footer />
      </body>
    </html>
  );
}
